# https://taskfile.dev

version: "3"

tasks:
  dev:
    cmds:
      - |
        ./watch.sh & \
        docker run --rm \
        --name slate \
        -p 4567:4567 \
        -v $(pwd)/source:/srv/slate/source \
        slatedocs/slate serve

  build:
    cmds:
      - ./compile.sh
